AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda to store auditing events coming from a Kinesis stream
Parameters:
    Stack:
        Description: Stack name
        Type: String
        Default: cms-fronts
    App:
        Description: Application name
        Type: String
        Default: auditing-store-events-lambda
    Stage:
        Description: Stage name
        Type: String
        AllowedValues:
            - CODE
            - PROD
        Default: CODE
    EventSourceKinesisStream:
        Description: Kinesis stream emitting update events
        Type: String
Resources:
    ExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - Effect: Allow
                      Principal:
                        Service:
                            - lambda.amazonaws.com
                      Action: "sts:AssumeRole"
            Path: /
            Policies:
                - PolicyName: consumeKinesis
                  PolicyDocument:
                    Statement:
                        Effect: Allow
                        Action:
                            - "kinesis:GetRecords"
                            - "kinesis:GetShardIterator"
                            - "kinesis:DescribeStream"
                            - "kinesis:ListStreams"
                        Resource: &kinesisArn
                            "Fn::Join":
                                - ""
                                -
                                    - "arn:aws:kinesis:"
                                    - Ref: "AWS::Region"
                                    - ":"
                                    - Ref: "AWS::AccountId"
                                    - ":stream/"
                                    - Ref: EventSourceKinesisStream
                - PolicyName: listStreams
                  PolicyDocument:
                    Statement:
                        Effect: Allow
                        Action:
                            - "kinesis:ListStreams"
                        Resource: "*"
                - PolicyName: logs
                  PolicyDocument:
                    Statement:
                        Effect: Allow
                        Action:
                            - "logs:CreateLogGroup"
                            - "logs:CreateLogStream"
                            - "logs:PutLogEvents"
                        Resource: "arn:aws:logs:*:*:*"
                - PolicyName: lambda
                  PolicyDocument:
                    Statement:
                        Effect: Allow
                        Action:
                            - "lambda:InvokeFunction"
                        Resource: "*"
                - PolicyName: elasticSearch
                  PolicyDocument:
                    Statement:
                        Effect: Allow
                        Action:
                            - "es:ESHttpPost"
                        Resource: "arn:aws:es:eu-west-1:163592447864:domain/auditing/*"
    Lambda:
        Type: AWS::Lambda::Function
        Properties:
            Code:
                S3Bucket: auditing-lambda-dist
                S3Key:
                    "Fn::Join":
                        - "/"
                        -
                            - Ref: Stage
                            - artifact.zip
            Description: Decode Thrift events and store them
            Handler: index.handler
            MemorySize: 128
            Role:
                "Fn::GetAtt": ["ExecutionRole", "Arn"]
            Runtime: nodejs
            Timeout: 60
    EventSource:
        Type: AWS::Lambda::EventSourceMapping
        Properties:
            BatchSize: 100
            Enabled: true
            EventSourceArn:
                *kinesisArn
            FunctionName:
                Ref: Lambda
            StartingPosition: LATEST
